//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebLocamer.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class info_option
    {
        public Nullable<int> quantité { get; set; }
        public Nullable<int> durée { get; set; }
        public int id_option { get; set; }
        public int id_sejour { get; set; }
    
        public virtual option option { get; set; }
        public virtual Sejour Sejour { get; set; }
    }
}
